#!/bin/python
import getopt
import sys
import os
import json
import datetime
from typing import Any

import requests

section = "languages"
exclude_langs: list[str] = []
include_langs: list[str] = []

use_included_total = 0

print_reversed = 0

milestones: list[float | int] = [50]

time_milestones: list[str] = []

api = ""
user = ""

top = -1

ansi_enabled = sys.stdout.isatty()

valid_ranges=[
    "today",
    "yesterday",
    "week",
    "month",
    "year",
    "last_7_days",
    "7_days",
    "last_30_days",
    "30_days",
    "last_6_months",
    "6_months",
    "last_12_months",
    "12_months",
    "last_year",
    "any",
    "all_time"
]

used_range = "any"
start_time = ""
end_time = ""

read_from = ""
data_fmt = "stats"

def gen_help():
    print(f"""lang-stats [TprxiautAefSERl] [percentage...]
        Use wakapi to print language/project usage stats

        OPTIONS:
        u <user>           : the user to print stats for
        l                  : print the leaderboard
        t <number>         : display the top <number> languages/projects
        p                  : print project times instead of language times
        r <range>          : time range, one of:
        R                  : print from least -> greatest
                                {"\n\t\t\t\t".join(valid_ranges)}
        x <names>          : exclude a ',' separated list of languages/projects
                             can be used multiple times.
                             Mutually exclusive with -i
        i <names>          : Similar to -x but ONLY show the languages listed with -i
                             Mutually exclusive with -x
        T                  : When using -x or -i,
                             use only the sum of the time from the included languages/projects
                             as the total time instead of the total time of ALL languages/projects
        a <domain>         : use <domain> as the api url base
        A                  : disbale ansi sequences
                             (automatically disabled when stdout is not a terminal)
        e                  : enable ansi sequences

        f <file>           : read stats form a file (-) for stdin
        F <   summary      : set the data format stats, summary, or leaders
            | stats          settings to leaders will display a leaderboard
            | leaders
          >
                           : also sets -r to today (use -r after to override)
        -S <start>         : start time
                             sets -F to summary as it's necessary
                             also sets -r to ''
        -E <end>           : end time
                             sets -F to summary as it's necessary
                             also sets -r to ''

        ARGUMENTS:
        percentage... :
                    each arg is treated as a percentage to print to label how many
                    languages are needed to add up to that percentage.
""")

args = sys.argv
opts, args = getopt.getopt(args[1:], "hTpr:x:i:a:u:t:Aef:F:S:E:R")

for opt, optarg in opts:
    match opt[1:]:
        case "t":
            top = int(optarg)
        case "p":
            section = "projects"
        case "R":
            print_reversed = 1
        case "r":
            used_range = optarg
            shortcuts = {
                    "t": "today",
                    "w": "week",
                    "m": "month",
                    "30": "last_30_days",
            }
            used_range = shortcuts.get(used_range, used_range)

            if used_range not in valid_ranges:
                print(f"Not a valid range: {used_range} setting back to any",
                      file=sys.stderr)
        case "T":
            use_included_total = 1
        case "x":
            include_langs = []
            exclude_langs += [k.strip().lower() for k in optarg.split(",")]
        case 'i':
            exclude_langs = []
            include_langs += [k.strip().lower() for k in optarg.split(",")]
        case 'a':
            api = optarg
        case 'u':
            user = optarg
        case 'e':
            ansi_enabled = 1
        case 'A':
            ansi_enabled = 0
        case 'f':
            read_from = optarg
        case 'S':
            used_range = ""
            start_time = optarg
        case 'E':
            used_range = ""
            end_time = optarg
        case 'F':
            data_fmt = optarg
            used_range = "today"
        case 'h':
            gen_help()
            exit()
        case INVALID:
            print(f"Invalid option {INVALID}", file=sys.stderr)
            exit(1)

if not api:
    print("No api url given", file=sys.stderr)
    exit(1)

if not user and data_fmt != "leaders":
    print("No user given", file=sys.stderr)
    exit(1)

def convertsecs(secs: int):
    h = secs // 3600
    m = (secs % 3600) // 60
    s = secs % 60
    return f"{h:02d}:{m:02d}:{s:02d}"

def time2secs(time: str):
    hours, mins, secs = time.split(":")
    return int(hours) * 3600 + int(mins) * 60 + int(secs)

def lang_counter():
    langs_included = 0

    def include_lang(lang: str):
        nonlocal langs_included

        lang = lang.lower()

        if top > 0 and langs_included > top:
            return False

        langs_included += 1

        if exclude_langs and lang in exclude_langs:
            return False
        elif exclude_langs:
            return True

        if include_langs and lang in include_langs:
            return True
        elif include_langs:
            return False

        return True

    return include_lang

if args:
    milestones = []
    time_milestones = []
    for arg in args:
        if ":" in arg:
            time_milestones.append(arg)
        else:
            milestones.append(float(arg))

if read_from:
    if read_from == "-":
        raw = json.loads("".join(sys.stdin.readlines()))
    else:
        with open(read_from) as f:
            raw = json.load(f)
elif data_fmt == "stats":
    raw = requests.get(f"{api}/api/compat/wakatime/v1/users/{user}/stats/{used_range}")
    raw = raw.json()
elif data_fmt == "leaders":
    req = requests.get(f"{api}/api/compat/wakatime/v1/leaders")
    raw = req.json()
else:
    key = os.getenv("WAKA_KEY")
    if not key:
        print("the $WAKA_KEY env var must be set to use -F without -f", file=sys.stderr)
        exit(1)
    params = {}
    if used_range:
        params["range"] = used_range
    elif start_time == '' or end_time == '':
        print("Cannot use -F summary with no -f without setting -S AND -E", file=sys.stderr)
        exit(1)
    if start_time:
        params["start"] = start_time
        params["end"] = end_time
    raw = requests.get(f"{api}/api/compat/wakatime/v1/users/{user}/summaries", params=params, headers={
        "Authorization": f"Basic {key}"
        })
    raw = raw.json()
# print(json.dumps(raw))

def print_line_item(name: str, time: str, pct: float, *, clr="35"):
    text = f"\x1b[{clr}m{name}\x1b[0m" if ansi_enabled else name
    text += f" {time} ({pct:.2f}%)"
    text += "\x1b[0m" if ansi_enabled else ""
    print(text)

def get_clr_from_list_and_cur(l: list[Any], cur: int):
    if print_reversed and len(l) - cur < 6:
        return f"3{len(l) - cur}"
    elif not print_reversed and cur < 6:
        return f"3{cur + 1}"
    else:
        return "0"

def language_printer():
    lang_count = 0

    total_pct = 0
    total_secs = 0

    milestones_iter =  iter(sorted(milestones))
    cur_milestone = next(milestones_iter, -1)

    time_milestones_iter = iter(sorted(time_milestones, key=time2secs))
    cur_time_milestone = next(time_milestones_iter, "")

    def print_lang_list(langs, total_secs_included: int):
        nonlocal total_pct, total_secs, lang_count, cur_milestone, cur_time_milestone

        for i, item in enumerate(langs):
            name = item["name"]

            secs = item["total_seconds"]

            if use_included_total:
                pct = secs / total_secs_included * 100
            else:
                pct = item["percent"]

            total_pct += pct

            total_secs += secs
            lang_count += 1

            clr = get_clr_from_list_and_cur(langs, i)

            print_line_item(name, convertsecs(secs), pct, clr=clr)

            while cur_milestone > 0 and total_pct > cur_milestone:
                print_line_item(f"{cur_milestone}%-({lang_count})", convertsecs(total_secs), total_pct, clr="35;1")
                # print(f"\x1b[1m{cur_milestone}%-({lang_count}) {convertsecs(total_secs)} ({total_pct:.2f}%)\x1b[0m")
                cur_milestone = next(milestones_iter, -1)

            while cur_time_milestone and total_secs > time2secs(cur_time_milestone):
                print_line_item(f"{cur_time_milestone}-({lang_count})", convertsecs(total_secs), total_pct, clr="95")
                # print(f"\x1b[1m{cur_time_milestone}-({lang_count}) {convertsecs(total_secs)} ({total_pct:.2f}%)\x1b[0m")
                cur_time_milestone = next(time_milestones_iter, "")

        return total_secs, total_pct

    return print_lang_list

def handle_stats(stats, label = "", print_reversed = print_reversed):
    if label:
        print(f"------------------\n{label}\n------------------")

    if print_reversed:
        stats = [*reversed(stats)]

    time_total = day_count * 86400

    total_secs_included = 0

    include = lang_counter()
    langs = []
    for item in stats:
        name = item["name"]
        if not include(name):
            continue
        total_secs_included += item["total_seconds"]
        langs.append(item)

    printer = language_printer()

    total_secs, total_pct = printer(langs, total_secs_included)

    print(f"--------------\nTOTAL: {convertsecs(total_secs)} ({total_pct:.02f}%)")
    print(f"--------------\nAVG {convertsecs(round(total_secs / time_total * 86400))} time/day\n")


if data_fmt == "leaders":
    data = raw

    dash_T = use_included_total

    if not use_included_total:
        total_time = sum(k["running_total"]["total_seconds"] for k in data["data"])
        use_included_total = 1
    else:
        total_time = 0
        for i, user in enumerate(data["data"]):
            include = lang_counter()
            for item in user["running_total"]["languages"]:
                if not include(item["name"]): continue
                total_time += item["total_seconds"]

    printer = language_printer()

    for i, user in enumerate(data["data"]):
        include = lang_counter()
        langs = [item for item in user["running_total"]["languages"] if include(item["name"])]
        if not dash_T:
            user_total = user["running_total"]["total_seconds"]
        else:
            user_total = sum(l["total_seconds"] for l in langs)
        clr = get_clr_from_list_and_cur(data["data"], i)
        print("----------")
        print_line_item(f"{user["user"]["display_name"]}", convertsecs(user_total), user_total / total_time * 100, clr=clr)
        printer(langs, total_time)

    exit()
elif data_fmt == "summary":
    data = raw
    day_count = data["daily_average"]["days_including_holidays"]
    for day in data["data"]:
        start = day["range"]["start"][0:19]
        end = day["range"]["end"][0:19]
        day = day[section]
        if day:
            handle_stats(day, f'{datetime.datetime.strptime(start, "%Y-%m-%dT%H:%M:%S")} -> {datetime.datetime.strptime(end, "%Y-%m-%dT%H:%M:%S")}')
    exit()

data = raw["data"]
if data_fmt == "stats":
    day_count = data["days_including_holidays"] + 1
else:
    day_count = raw["daily_average"]["days_including_holidays"]

data = data[section]
handle_stats(data, "")
